### PR TITLE
Ava/review [Intro]

### PR DESCRIPTION
**Pull request by avahoffman**
***General:***

- This is awesome and super well done!!! ✨
- Did some nitpicky capitalization of H1s and noticed H2s and H3s aren’t super consistent.. might want to do a quick edit on these.
- Added “course”/section headers (don’t think these show up in lean pub, though they look nice and help keep things organized in the book down)

***Specifics:***

About

Should this go somewhere else? It's actually rendering and printing on the "About" page
https://github.com/datatrail-jhu/DataTrail/blob/582d2a440e347b08478276e42e31fda76aed62b4/00_intro_01_welcome.Rmd#L7-L13
image

1.1.1

I think it’s hard to see where different “courses” (Intro, Getting Data, Plotting Data, etc) start. I added course headers, but these only show up on bookdown, not on Leanpub. Might be helpful to orient them and make sure language is consistent throughout, eg.,
- The whole program is called datatrail
- each numbered page on the table of contents (left) is a chapter. 

1.1.2

This is awesome! Minor comment - one thing that kind of depresses me is that much commercial data science boils down to “show you a tailored ad”. I wonder if it’s worth using another example too? https://www.discoverdatascience.org/social-good/nonprofits/ has some neat examples, like helping the Red Cross find counties to target for smoke alarm installation campaigns. Also https://www.datakind.org/what-we-do

1quiz

Might want to use `random-choice-order: false` with “all of the above” for set answer order

2

Love this! Might be worth mentioning that search results can vary slightly person to person because google tries to tailor to your needs and interests.

2.0.2

Is the Basecamp open to the public? Seems like it’s something that’s more in its own category as it’s specific to the fellows/cohort (I think). Also these links did not work for me and tried to point to other content on leanpub.

3

Changed title so it’s not a question. Blasted question marks on leanpub lol

Might also be nice to have a shortcut glossary at the end.

3.1.2

Would be nice in general if links opened in a new tab, because when navigating back in the browser it doesn’t take me to the last place I was reading. Sometimes it also seems to affect functionality. For example, if I click https://docs.google.com/ it gives an error, but if I right click into a new tab, it works as expected.

3.1.4

http://rstudio.cloud These links do not open unless I open in a new tab

3.3 

Screenshots show slack, not basecamp

3.5.1

Might suggest song lyrics instead of or in addition to book or poem

3.7.2

 https://support.google.com/chromebook Doesn’t work unless opened in a new tab

4

Noticed the term “local” is used throughout, and they might not know what this means.. Is it defined anywhere, in contrast to cloud? 

4.0.3

Is there any discussion of connecting to “sketchy” networks? Might be a thing to bring up.

5.3.8

They already did the offline setup in a previous section, so I’d change the language to “make sure the box is checked” so they don’t get confused and uncheck it

5.3.9

Will they be expected to buy more storage? I think some kind of “don’t worry, you shouldn’t need to buy any storage for DataTrail” message would be nice and assuage any fears/concerns

5.4.1

I think just have them do the “Join with Google” option

### CODE REVIEW

**Comment by cansavvy** [comment]
> Should this go somewhere else?

It has to go somewhere because there's not a way to specify these options on the Leanpub GUI. But I don't know where is the least obtrusive place.

**Comment by avahoffman** [comment]
> > Should this go somewhere else?
> 
> It has to go somewhere because there's not a way to specify these options on the Leanpub GUI. But I don't know where is the least obtrusive place.

**Comment by avahoffman** [comment]
> > Should this go somewhere else?
> 
> It has to go somewhere because there's not a way to specify these options on the Leanpub GUI. But I don't know where is the least obtrusive place.

Would something like #31 work? Basically, concatenating those params on to any md file once they are transferred over to `manuscript/` ?

**Comment by cansavvy** [comment]
> Would something like #31 work? Basically, concatenating those params on to any md file once they are transferred over to `manuscript/` ? I'm not super familiar with the leanpub mechanics. Could you use a completely separate `.md` not listed in Book.txt?

I'll try this out! This might be a good solution! Thanks!

**Review by cansavvy — APPROVED** [review]
Thanks for all these comments! I've added some more things based on your review here! This is super helpful! I really appreciate the work you put into this!

**Comment by avahoffman** [comment]
Woo ! Happy to help!

**Comment by avahoffman** [comment]
I don't have permission to merge, please feel free to take charge of merging!

**Pull request merged**
