### PR TITLE
Update dictionary.txt

### PR DESCRIPTION
**Pull request by avahoffman**
The dictionary was not ordered - hard to see what was there

### CODE REVIEW

**Review by allissadillman — APPROVED** [review]
looks good!

**Review by carriewright11 — CHANGES_REQUESTED** [review]
Looks good! Looks like there are also some broken urls worth investigating

**Comment by carriewright11** [comment]
@avahoffman  I was also fixing the urls in PR #47

**Comment by carriewright11** [comment]
We can also just ignore my PR

**Comment by carriewright11** [comment]
Looks like Ava's fixes were processed faster than mine, so let's just go with them for now.

**Comment by avahoffman** [comment]
Thanks @carriewright11 !

**Pull request merged**
